### ISSUE TITLE
Waku 0: setup cross-testing of Waku clients and Waku nodes

### ISSUE THREAD

**Issue by adambabik** [vacp2p/pm#3]
# Problem

We are going to implement Waku clients and Waku nodes in Nim and Go. It's important that they both properly communicate with each other.

This cross-communication should be tested automatically, ideally for each new PR in either of Nim or Go repo.

# Acceptance criteria

1. Cross-communication between Waku clients and Waku nodes is tested for each PR.
2. Multiple tests can be executed on the same server (our CI requirement).
3. The whole test suite executes in short amount of time so that it does not disturb development.

# Possible Solutions

1. Run a pairs of containers one with a Waku client and another with Waku node. All combinations of implementations should be tested.

**Comment by oskarth** [comment]
@adambabik @kdeme  is still happening or no?
