### ISSUE TITLE
Waku: Deploy Waku nodes with Waku-Whisper bridge nodes for cluster

### ISSUE THREAD

**Issue by oskarth** [vacp2p/pm#4]
# Problem

As a developer, I want to test end to end integration of Waku nodes with an environment as close to production as possible.

(Later for `waku/1`) As a user, I want to have the ability to use Waku mode to reduce my bandwidth usage. Additionally, I want to have compatibility with Whisper networks so I can receive and send messages to people not using the waku subprotocol.

## Acceptance criteria

There are nodes running Waku-Whisper bridge in our cluster, such that if I connect to them (directly hardcoded like mailserver e.g., later discovered) using Waku node I can send and receive to clients using Whisper.

## Details

As part of Waku, we want to deploy Waku nodes to our cluster for experimental end to end testing. These are running the subprotocol `waku/0` and bridge traffic. See https://specs.vac.dev/waku.html#backwards-compatibility for more details.

Currently the only implementation that supports this is `nim-eth`. This means we want to deploy `nim-eth` with Waku capability and Waku Whisper bridge enabled. This will also be a great opportunity to ensure our app can actually interop successfully with the Nim based impl (should be fine but...you know).

Right now I'm not quite clear what changes we need to make to the `nim-eth` client, but I suppose we need to expose some CLI flags and then put it in a terraform/ansible playbook?

fyi @jakubgs (cluster) @kdeme (nim-eth) @cammellos (app) @adambabik (go/cluster)

**Comment by jakubgs** [comment]
@kdeme maybe we could do a 1-on-1 and talk about how this `waku` node is supposed to run, and what the result is supposed to be.

**Comment by oskarth** [comment]
@jakubgs @kdeme I feel like there was some follow up to this but can't find it. Can you please link the relevant issue back here?

**Comment by kdeme** [comment]
Sure: https://github.com/status-im/nimbus/issues/426

**Comment by oskarth** [comment]
I believe this has been done.
