### ISSUE TITLE
Waku 0: collect metrics

### ISSUE THREAD

**Issue by adambabik** [vacp2p/pm#6]
# Problem

From day 1, app-level metrics should be collected by Waku client and Waku node and exposed through some interface. The goal is to have insights into how the process operates.

# Acceptance criteria

TBD: a list of metrics to collect in Waku client and Waku node.

# Details

We want to know exactly how many packets and bandwidth is used during the communication between Waku client and Waku node. When using Whisper, we have metrics collected for Whisper server nodes but we don't collect any low-level metrics for Whisper light nodes (Whisper service running on the app).

# Possible Solutions

TBD

**Comment by oskarth** [comment]
Above still applies, but it doesn't belong in specs repo regardless

**Comment by oskarth** [comment]
Implemented in nim-eth btw, can probably re-use these events https://github.com/status-im/nim-eth/issues/110

**Comment by oskarth** [comment]
This would also make simulation comparison better, e.g. https://github.com/vacp2p/simulations/issues/1#issuecomment-567340683

**Comment by oskarth** [comment]
Unrelated to Vac PM. Done in spec and Nim implementation. If more needs to be done in Go implementation it should be captured in that repo (can't transfer due to different org).
